name: "iSpy Agent DVR Test"
version: 4.9.3.0.2
slug: ispy_agent_dvr
description: "Test"
url: "https://github.com/DivanX10/Home-Assistant-Add-on-DeepStack-Edge"
startup: application
init: false
ingress: true
panel_icon: mdi:cctv
arch:
  - amd64
  - aarch64
  - armv7
boot: auto
hassio_api: true
map:
  - config:rw
  - share:rw
advanced: true  
ports:
  8090/tcp: 8090
  3478/udp: 3478
  50000/udp: 50000
  50001/udp: 50001
  50002/udp: 50002
  50003/udp: 50003
  50004/udp: 50004
  50005/udp: 50005
  50006/udp: 50006
  50007/udp: 50007
  50008/udp: 50008
  50009/udp: 50009
  50010/udp: 50010
ports_description:
  8090/tcp: "Main UI port. Default port"
  3478/udp: "STUN server port, don't change"
  50000/udp: "TURN server UDP port range. Default port, don't change"
  50001/udp: "TURN server UDP port range. Default port, don't change"
  50002/udp: "TURN server UDP port range. Default port, don't change"
  50003/udp: "TURN server UDP port range. Default port, don't change"
  50004/udp: "TURN server UDP port range. Default port, don't change"
  50005/udp: "TURN server UDP port range. Default port, don't change"
  50006/udp: "TURN server UDP port range. Default port, don't change"
  50007/udp: "TURN server UDP port range. Default port, don't changee"
  50008/udp: "TURN server UDP port range. Default port, don't change"
  50009/udp: "TURN server UDP port range. Default port, don't changee"
  50010/udp: "TURN server UDP port range. Default port, don't change"
options:
  folder_path: /share/agentdvr
schema:
  folder_path: str
